extends TestSuite
## PRD-03 R16 — the `Library` loader: indexing, lookup, fuzzy name resolution and graceful
## degradation.
##
## [b]What this suite deliberately does not do:[/b] `res://data/exercise_library.json` is
## owned by PRD-04 and is being generated by another agent, so no assertion here depends on
## its contents or its record count. Everything is tested against a small fixture library
## written into `res://.test_tmp/library/`, plus a smoke test that only checks the real file
## is *self-consistent* when it happens to exist.
##
## Fixture files live under `res://.test_tmp/` because `user://` is read-only on this
## machine (ADR-04).

const LIBRARY_SCRIPT := "res://scripts/autoload/library.gd"
const TMP_ROOT := "res://.test_tmp/"
const SUITE_DIR := "res://.test_tmp/library/"
const FIXTURE := "res://.test_tmp/library/fixture.json"
const REAL_LIBRARY := "res://data/exercise_library.json"


class Probe extends RefCounted:
	var events: Array[String] = []

	func record(text: String) -> void:
		events.append(text)

	func count_of(prefix: String) -> int:
		var total := 0
		for event in events:
			if event.begins_with(prefix):
				total += 1
		return total

	func last() -> String:
		return events[events.size() - 1] if not events.is_empty() else ""


func _init() -> void:
	suite_name = "library"


func run() -> void:
	_write_gdignore()
	_test_missing_file()
	_test_malformed_files()
	_test_fixture_indexes()
	_test_lookup_and_catalog()
	_test_resolve_name()
	_test_skipped_records()
	_test_reload_and_idempotence()
	_test_real_library_smoke()
	_cleanup()


# ------------------------------------------------------------------ graceful degradation

func _test_missing_file() -> void:
	begin("a missing library file degrades gracefully and never throws")
	_fresh()
	var path := SUITE_DIR + "does_not_exist.json"
	var probe := Probe.new()
	var library := _library(probe)

	assert_false(library.load_library(path), "load_library returns false")
	assert_false(library.is_ready(), "is_ready() is false")
	assert_eq(probe.count_of("library_failed"), 1, "library_failed was emitted")
	assert_true(probe.last().contains("not found"), "the reason names the problem")
	assert_eq(library.count(), 0, "count() is zero")
	assert_empty(library.all_exercises(), "all_exercises() is empty")
	assert_empty(library.all_ids(), "all_ids() is empty")
	assert_empty(library.get_exercise("bench-press"), "get_exercise() returns {}")
	assert_false(library.has_exercise("bench-press"), "has_exercise() is false")
	assert_empty(library.by_area("chest"), "by_area() is empty")
	assert_empty(library.by_equipment("barbell"), "by_equipment() is empty")
	assert_empty(library.stretches(), "stretches() is empty")
	assert_empty(library.search("bench"), "search() is empty")
	assert_empty(library.catalog_compact(), "catalog_compact() is empty")
	assert_empty(library.catalog_filtered(PackedStringArray(["chest"]), PackedStringArray()),
		"catalog_filtered() is empty")
	assert_empty(library.catalog_prompt_lines(), "catalog_prompt_lines() is empty")
	assert_eq(library.resolve_name("bench press"), "", "resolve_name() returns an empty id")
	assert_empty(library.get_frames("bench-press"), "get_frames() is empty")
	assert_empty(library.get_cues("bench-press"), "get_cues() is empty")
	assert_eq(library.name_of("bench-press"), "", "name_of() is empty")
	assert_empty(library.areas_of("bench-press"), "areas_of() is empty")
	assert_false(library.is_compound("bench-press"), "is_compound() is false")
	assert_empty(library.source_attribution(), "source_attribution() is {}")
	assert_false(library.failure_reason().is_empty(), "the failure reason is kept")
	library.free()


func _test_malformed_files() -> void:
	begin("every malformed shape fails the same quiet way")
	var cases: Array[Array] = [
		["invalid_json", "{ not json"],
		["array_root", "[{\"id\": \"bench-press\"}]"],
		["no_schema_version", JSON.stringify({"source": {"repo": "x"}, "exercises": []})],
		["float_schema_version_ok", JSON.stringify({"schema_version": 1.0,
			"source": {"repo": "x"}, "exercises": []})],
		["no_source", JSON.stringify({"schema_version": 1, "exercises": []})],
		["no_exercises", JSON.stringify({"schema_version": 1, "source": {"repo": "x"}})],
		["exercises_not_array", JSON.stringify({"schema_version": 1, "source": {"repo": "x"},
			"exercises": "nope"})],
	]
	var should_fail: PackedByteArray = PackedByteArray([1, 1, 1, 0, 1, 1, 1])
	for i in cases.size():
		var label: String = cases[i][0]
		var text: String = cases[i][1]
		var path := "%s%s.json" % [SUITE_DIR, label]
		_write_raw_absolute(path, text)
		var probe := Probe.new()
		var library := _library(probe)
		var ok: bool = library.load_library(path)
		if should_fail[i] == 1:
			assert_false(ok, "%s is rejected" % label)
			assert_false(library.is_ready(), "%s leaves is_ready() false" % label)
			assert_eq(probe.count_of("library_failed"), 1, "%s emits library_failed" % label)
			assert_eq(library.count(), 0, "%s exposes no records" % label)
			assert_eq(library.resolve_name("bench press"), "", "%s resolves nothing" % label)
		else:
			assert_true(ok, "%s is accepted (a JSON 1.0 is an integer version)" % label)
			assert_true(library.is_ready(), "%s is ready" % label)
			assert_eq(probe.count_of("library_loaded"), 1, "%s emits library_loaded" % label)
		library.free()

	begin("an empty but well-formed library is ready and empty")
	var empty_path := SUITE_DIR + "empty_ok.json"
	_write_raw_absolute(empty_path, JSON.stringify({
		"schema_version": 1, "source": {"repo": "x"}, "exercises": [],
	}) + "\n")
	var empty_probe := Probe.new()
	var empty_library := _library(empty_probe)
	assert_true(empty_library.load_library(empty_path), "an empty exercise list is legal")
	assert_true(empty_library.is_ready(), "is_ready() is true")
	assert_eq(empty_library.count(), 0, "but there is nothing in it")
	assert_eq(empty_probe.count_of("library_loaded"), 1, "library_loaded(0) is emitted")
	empty_library.free()


# ------------------------------------------------------------------ indexes

func _test_fixture_indexes() -> void:
	begin("the fixture library loads and indexes")
	_write_fixture()
	var probe := Probe.new()
	var library := _library(probe)
	assert_true(library.load_library(FIXTURE), "the fixture loads")
	assert_true(library.is_ready(), "is_ready() is true")
	assert_eq(library.count(), 5, "five usable records (two are skipped)")
	assert_eq(probe.count_of("library_loaded"), 1, "library_loaded was emitted")
	assert_eq(probe.last(), "library_loaded:5", "with the record count")

	begin("records are reachable by id and name")
	var bench: Dictionary = library.get_exercise("bench-press")
	assert_eq(bench.get("name", ""), "Bench Press", "the record carries its name")
	assert_eq(library.name_of("bench-press"), "Bench Press", "name_of() agrees")
	assert_eq(library.name_of("nope"), "", "an unknown id has no name")
	assert_true(library.has_exercise("bench-press"), "has_exercise() is true")
	assert_false(library.has_exercise("nope"), "has_exercise() is false for an unknown id")
	assert_empty(library.get_exercise("nope"), "get_exercise() returns {} for an unknown id")
	assert_eq(library.get_exercise("bench-press").get("equipment", ""), "barbell", "equipment")
	assert_true(library.is_compound("bench-press"), "compound is true")
	assert_false(library.is_compound("world-greatest-stretch"), "a stretch is not compound")
	assert_false(library.is_compound("nope"), "is_compound() is false for an unknown id")
	assert_true(bench.get("default_sets", 0) is int, "JSON floats become ints (default_sets)")
	assert_eq(bench.get("default_sets", 0), 3, "default_sets value")
	assert_eq(bench.get("rest_seconds", 0), 90, "rest_seconds value")
	assert_true(bench.get("areas", []) is Array, "a record keeps a plain Array for areas")

	begin("frames and cues come back as PackedStringArray")
	var frames: PackedStringArray = library.get_frames("bench-press")
	assert_eq(frames.size(), 3, "three frames")
	assert_true(frames[0].begins_with("res://assets/exercises/"), "frames are resource paths")
	assert_empty(library.get_frames("nope"), "an unknown id has no frames")
	var cues: PackedStringArray = library.get_cues("bench-press")
	assert_eq(cues.size(), 3, "three cues")
	assert_empty(library.get_cues("nope"), "an unknown id has no cues")
	assert_eq(library.areas_of("bench-press"), PackedStringArray(["chest"]), "areas_of()")
	assert_empty(library.areas_of("nope"), "an unknown id has no areas")

	begin("area, equipment and stretch indexes")
	assert_eq(library.by_area("chest").size(), 1, "one chest exercise")
	assert_eq(library.by_area("chest")[0].get("id", ""), "bench-press", "and it is the bench")
	assert_eq(library.by_area("legs").size(), 1, "one legs exercise")
	assert_eq(library.by_area("cardio").size(), 0, "no cardio in the fixture")
	assert_eq(library.by_equipment("barbell").size(), 3, "three barbell exercises")
	assert_eq(library.by_equipment("bodyweight").size(), 2, "two bodyweight exercises")
	assert_eq(library.by_equipment("cable").size(), 0, "no cable exercises")
	assert_eq(library.stretches().size(), 2, "two stretches")
	assert_eq(library.stretches()[0].get("is_stretch", false), true, "stretches are stretches")
	assert_eq(library.all_ids().size(), 5, "five ids")
	assert_eq(library.all_ids()[0], "bench-press", "ids are sorted")
	assert_eq(library.all_ids()[4], "world-greatest-stretch", "ids are sorted (last)")
	assert_eq(library.all_exercises().size(), 5, "all_exercises() matches count()")

	begin("source attribution is exposed for the attribution screen")
	var source: Dictionary = library.source_attribution()
	assert_eq(source.get("repo", ""), "https://example.invalid/exercises", "the source repo")
	assert_eq(source.get("license", ""), "CC0-1.0", "the licence")
	library.free()


func _test_lookup_and_catalog() -> void:
	begin("search matches names and ids, case-insensitively")
	_write_fixture()
	var library := _library(null)
	assert_true(library.load_library(FIXTURE), "fixture loaded")
	assert_eq(library.search("bench").size(), 1, "a name substring")
	assert_eq(library.search("BENCH").size(), 1, "search is case-insensitive")
	assert_eq(library.search("row").size(), 1, "another name substring")
	assert_eq(library.search("nope").size(), 0, "no match, no results")
	assert_eq(library.search("").size(), 0, "an empty query returns nothing")
	assert_eq(library.search("e", 1).size(), 1, "the limit is honoured")
	assert_eq(library.search("e", 2).size(), 2, "a higher limit returns more")

	begin("catalog_compact has exactly the four documented keys")
	var catalog: Array[Dictionary] = library.catalog_compact()
	assert_eq(catalog.size(), 5, "one entry per record")
	var keys := PackedStringArray()
	for key in catalog[0]:
		keys.append(String(key))
	keys.sort()
	assert_eq(keys, PackedStringArray(["areas", "equipment", "id", "name"]),
		"catalog_compact keys are [id, name, areas, equipment]")
	assert_eq(catalog[0].get("id", ""), "bench-press", "id-sorted")
	assert_eq(catalog[0].get("name", ""), "Bench Press", "name")
	assert_eq(catalog[0].get("areas", PackedStringArray()), PackedStringArray(["chest"]),
		"areas")
	assert_true(catalog[0].get("equipment", "") is String, "equipment is a string")

	begin("catalog_prompt_lines is one line per record, id-sorted")
	var lines: PackedStringArray = library.catalog_prompt_lines()
	assert_eq(lines.size(), 5, "five lines")
	assert_true(lines[0].begins_with("bench-press | Bench Press | "), "the line format")
	assert_true(lines[0].contains("chest"), "areas are listed")
	assert_true(lines[0].ends_with("barbell"), "equipment closes the line")

	begin("catalog_filtered treats an empty filter as no constraint")
	assert_eq(library.catalog_filtered(PackedStringArray(), PackedStringArray()).size(), 5,
		"no filters, everything")
	assert_eq(library.catalog_filtered(PackedStringArray(["legs"]), PackedStringArray()).size(), 1,
		"one legs exercise")
	assert_eq(library.catalog_filtered(PackedStringArray(), PackedStringArray(["dumbbell"])).size(),
		0, "no dumbbell exercises in the fixture")
	assert_eq(library.catalog_filtered(PackedStringArray(["chest", "back"]),
		PackedStringArray(["barbell"])).size(), 2, "two barbell upper-body exercises")
	assert_eq(library.catalog_filtered(PackedStringArray(["mobility"]),
		PackedStringArray(["barbell"])).size(), 0, "filters combine with AND")
	library.free()


func _test_resolve_name() -> void:
	begin("resolve_name maps user-typed names onto ids")
	_write_fixture()
	var library := _library(null)
	assert_true(library.load_library(FIXTURE), "fixture loaded")

	assert_eq(library.resolve_name("Bench Press"), "bench-press", "an exact name")
	assert_eq(library.resolve_name("bench press"), "bench-press", "lower case")
	assert_eq(library.resolve_name("Benchpress"), "bench-press", "a missing space (R18)")
	assert_eq(library.resolve_name("bench press (barbell)"), "bench-press",
		"a parenthetical equipment hint (R18)")
	assert_eq(library.resolve_name("Bench-Press"), "bench-press", "the id spelling")
	assert_eq(library.resolve_name("bent over row"), "bent-over-row", "a second exact name")
	assert_eq(library.resolve_name("Romainian Deadlift"), "romanian-deadlift",
		"a misspelling resolves through fuzzy matching")
	assert_eq(library.resolve_name("worlds greatest stretch"), "world-greatest-stretch",
		"a possessive spelling resolves")
	assert_eq(library.resolve_name("zzz"), "", "nonsense resolves to nothing (R18)")
	assert_eq(library.resolve_name(""), "", "an empty query resolves to nothing")
	assert_eq(library.resolve_name("bench press", 0.99), "bench-press",
		"an exact match passes a stricter threshold")
	assert_eq(library.resolve_name("Romainian Deadlift", 0.999), "",
		"a stricter threshold rejects a near miss")
	library.free()


# ------------------------------------------------------------------ skipped records

func _test_skipped_records() -> void:
	begin("records without an id or name are skipped, duplicate ids keep the first")
	var path := SUITE_DIR + "skips.json"
	var records: Array = [_fixture_record("bench-press", "Bench Press", ["chest"], "barbell"),
		_fixture_record("bench-press", "Bench Press Duplicate", ["chest"], "barbell"),
		_fixture_record("", "Nameless Id", ["chest"], "barbell"),
		_fixture_record("no-name", "", ["chest"], "barbell"),
		_fixture_record("kept-one", "Kept One", ["back"], "cable"),
	]
	_write_raw_absolute(path, JSON.stringify({
		"schema_version": 1,
		"source": {"repo": "https://example.invalid/exercises", "license": "CC0-1.0",
			"creator": "Fixture"},
		"exercises": records,
	}, "\t", true, false) + "\n")

	var probe := Probe.new()
	var library := _library(probe)
	assert_true(library.load_library(path), "the file loads despite the bad records")
	assert_true(library.is_ready(), "it is ready")
	assert_eq(library.count(), 2, "only two records are usable")
	assert_true(library.has_exercise("bench-press"), "the first duplicate wins")
	assert_eq(library.name_of("bench-press"), "Bench Press", "the first record's name is kept")
	assert_true(library.has_exercise("kept-one"), "the good record is kept")
	assert_false(library.has_exercise(""), "an id-less record is not indexed")
	assert_false(library.has_exercise("no-name"), "a name-less record is not indexed")

	begin("a record that is not an object is skipped too")
	var path2 := SUITE_DIR + "not_objects.json"
	_write_raw_absolute(path2, JSON.stringify({
		"schema_version": 1,
		"source": {"repo": "x"},
		"exercises": ["nope", 42, _fixture_record("only-one", "Only One", ["core"], "machine")],
	}, "\t", true, false) + "\n")
	var library2 := _library(null)
	assert_true(library2.load_library(path2), "the file loads")
	assert_eq(library2.count(), 1, "only the object record is usable")
	assert_eq(library2.by_area("core").size(), 1, "and it is indexed")
	library.free()
	library2.free()


func _test_reload_and_idempotence() -> void:
	begin("load_library is idempotent per path, reload() forces a re-read")
	var path := SUITE_DIR + "reload.json"
	_write_raw_absolute(path, JSON.stringify({
		"schema_version": 1,
		"source": {"repo": "x"},
		"exercises": [_fixture_record("first", "First", ["chest"], "barbell")],
	}, "\t", true, false) + "\n")
	var library := _library(null)
	assert_true(library.load_library(path), "first load succeeds")
	assert_eq(library.count(), 1, "one record")

	# Rewrite the file behind the library's back: an idempotent load keeps the cache.
	_write_raw_absolute(path, JSON.stringify({
		"schema_version": 1,
		"source": {"repo": "x"},
		"exercises": [
			_fixture_record("first", "First", ["chest"], "barbell"),
			_fixture_record("second", "Second", ["back"], "cable"),
		],
	}, "\t", true, false) + "\n")
	assert_true(library.load_library(path), "the idempotent call still reports success")
	assert_eq(library.count(), 1, "and did not re-read the file")

	assert_true(library.reload(), "reload() re-reads")
	assert_eq(library.count(), 2, "the new record is picked up")
	assert_true(library.has_exercise("second"), "the new id is indexed")
	assert_true(library.load_library(path), "a load after a successful load still succeeds")

	begin("a failed load clears the previous index instead of keeping stale records")
	var broken := SUITE_DIR + "broken_after_good.json"
	_write_raw_absolute(broken, "{ broken")
	assert_false(library.load_library(broken), "the broken file is rejected")
	assert_false(library.is_ready(), "is_ready() is false")
	assert_eq(library.count(), 0, "no stale records remain")
	assert_false(library.has_exercise("first"), "the previous index is gone")
	library.free()


func _test_real_library_smoke() -> void:
	begin("the bundled library, when present, is self-consistent")
	# PRD-04 owns res://data/exercise_library.json and is generating it concurrently, so
	# this asserts internal consistency only — never its contents or its record count.
	var library := _library(null)
	var exists := FileAccess.file_exists(REAL_LIBRARY)
	var ok: bool = library.load_library()
	if exists:
		assert_true(ok, "the bundled library loads")
		assert_true(library.is_ready(), "Library is ready at boot")
		assert_eq(library.all_ids().size(), library.count(), "every record has an id")
		assert_eq(library.catalog_compact().size(), library.count(), "every record is catalogued")
		assert_eq(library.catalog_prompt_lines().size(), library.count(), "one prompt line each")
		var ids: PackedStringArray = library.all_ids()
		var sorted_ids: PackedStringArray = ids.duplicate()
		sorted_ids.sort()
		assert_eq(ids, sorted_ids, "all_ids() is sorted")
		if library.count() > 0:
			var first_id: String = library.all_ids()[0]
			assert_true(library.has_exercise(first_id), "the first id resolves")
			assert_false(library.name_of(first_id).is_empty(), "every record has a name")
			assert_eq(library.get_frames(first_id).size(), 3, "every record has three frames")
			assert_eq(library.get_cues(first_id).size(), 3, "every record has three cues")
			var resolved: String = library.resolve_name(library.name_of(first_id))
			assert_false(resolved.is_empty(), "a record's own name resolves to an id")
			assert_eq(library.name_of(resolved), library.name_of(first_id),
				"and to the same display name")
	else:
		assert_false(ok, "without the file the loader reports failure")
		assert_false(library.is_ready(), "and is not ready")
	library.free()


# ------------------------------------------------------------------ helpers

func _library(probe: Probe) -> Node:
	var script: GDScript = load(LIBRARY_SCRIPT)
	var library: Node = script.new()
	if probe != null:
		library.library_loaded.connect(func(count: int) -> void:
			probe.record("library_loaded:%d" % count))
		library.library_failed.connect(func(reason: String) -> void:
			probe.record("library_failed:%s" % reason))
	return library


func _write_fixture() -> void:
	_fresh()
	var records: Array = [
		_fixture_record("bench-press", "Bench Press", ["chest"], "barbell"),
		_fixture_record("bent-over-row", "Bent Over Row", ["back"], "barbell"),
		_fixture_record("romanian-deadlift", "Romanian Deadlift", ["legs"], "barbell"),
		_fixture_record("world-greatest-stretch", "World's Greatest Stretch", ["mobility"],
			"bodyweight", true),
		_fixture_record("childs-pose", "Child's Pose", ["mobility"], "bodyweight", true),
	]
	_write_raw_absolute(FIXTURE, JSON.stringify({
		"schema_version": 1,
		"source": {
			"repo": "https://example.invalid/exercises",
			"license": "CC0-1.0",
			"creator": "Fixture",
		},
		"exercises": records,
	}, "\t", true, false) + "\n")


func _fixture_record(record_id: String, record_name: String, areas: Array, equipment: String,
		is_stretch: bool = false) -> Dictionary:
	var slug := record_id if not record_id.is_empty() else "unnamed"
	return {
		"id": record_id,
		"name": record_name,
		"exercise_type": "duration" if is_stretch else "weight_reps",
		"equipment": equipment,
		"primary_muscle": String(areas[0]) if not areas.is_empty() else "",
		"secondary_muscles": [],
		"areas": areas,
		"is_stretch": is_stretch,
		"compound": not is_stretch,
		"difficulty": "beginner",
		# Floats on purpose: JSON has no integer type, and the loader must normalise them.
		"frames": [
			"res://assets/exercises/%s/frame-1.png" % slug,
			"res://assets/exercises/%s/frame-2.png" % slug,
			"res://assets/exercises/%s/frame-3.png" % slug,
		],
		"cues": ["Cue one", "Cue two", "Cue three"],
		"default_sets": 3.0,
		"rep_min": 8.0,
		"rep_max": 10.0,
		"rest_seconds": 90.0,
	}


# ------------------------------------------------------------------ filesystem helpers

func _fresh() -> void:
	_remove_tree(SUITE_DIR)
	DirAccess.make_dir_recursive_absolute(SUITE_DIR)
	_write_gdignore()


func _write_gdignore() -> void:
	var path := TMP_ROOT + ".gdignore"
	if FileAccess.file_exists(path):
		return
	DirAccess.make_dir_recursive_absolute(TMP_ROOT)
	var file := FileAccess.open(path, FileAccess.WRITE)
	if file != null:
		file.store_string("# Generated by the PRD-03 test helper — keeps the importer out.\n")
		file.close()


func _remove_tree(dir_path: String) -> void:
	if not DirAccess.dir_exists_absolute(dir_path):
		return
	for entry in DirAccess.get_files_at(dir_path):
		DirAccess.remove_absolute(dir_path.path_join(entry))
	for entry in DirAccess.get_directories_at(dir_path):
		_remove_tree(dir_path.path_join(entry))
	DirAccess.remove_absolute(dir_path)


func _write_raw_absolute(path: String, text: String) -> void:
	var file := FileAccess.open(path, FileAccess.WRITE)
	if file == null:
		return
	file.store_string(text)
	file.close()


func _cleanup() -> void:
	_remove_tree(SUITE_DIR)
