extends SceneTree
func _init() -> void:
	print("--- parse_string on junk:")
	var a: Variant = JSON.parse_string("not json")
	print("  result=", a)
	print("--- JSON.new().parse on junk:")
	var j := JSON.new()
	var err := j.parse("not json")
	print("  err=", err, " data=", j.data)
	print("--- JSON.new().parse on good:")
	var k := JSON.new()
	print("  err=", k.parse("{\"a\": 1}"), " data=", k.data, " type=", typeof(k.data))
	var m := JSON.new()
	print("  array err=", m.parse("[1,2]"), " type=", typeof(m.data))
	var n := JSON.new()
	print("  string err=", n.parse("\"hi\""), " type=", typeof(n.data))
	print("--- str(1.0)=", str(1.0), " num=", String.num(1.0, 1))
	quit(0)
