#!/usr/bin/env bash
# MicroWorkout — Android APK build (PRD-00 §10 layer 4).
#
#   tools/build_android.sh debug     -> build/MicroWorkout-debug.apk  (unsigned-with-debug-key)
#   tools/build_android.sh release   -> build/MicroWorkout.apk        (signed with our release key)
#
# Uses the PREBUILT export template (gradle_build=false) because this machine has
# no Android NDK — see master plan §3 and ADR-01.
#
# The release keystore password never lives in git: it is generated once into
# build/keystore.properties (gitignored) and injected into export_presets.cfg only
# for the duration of the export.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GODOT="${GODOT_BIN:-$HOME/Applications/godot}"
export JAVA_HOME="${JAVA_HOME:-$HOME/dev/jdk-17}"
export ANDROID_HOME="${ANDROID_HOME:-$HOME/Android/Sdk}"
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export PATH="$JAVA_HOME/bin:$ANDROID_HOME/platform-tools:$PATH"

MODE="${1:-debug}"
BUILD_DIR="$ROOT/build"
PROPS="$BUILD_DIR/keystore.properties"
KEYSTORE="$BUILD_DIR/microworkout-release.keystore"
PRESETS="$ROOT/export_presets.cfg"

mkdir -p "$BUILD_DIR"

case "$MODE" in
  debug)   PRESET="Android Debug";   OUT="$BUILD_DIR/MicroWorkout-debug.apk"; FLAG="--export-debug" ;;
  release) PRESET="Android Release"; OUT="$BUILD_DIR/MicroWorkout.apk";       FLAG="--export-release" ;;
  *) echo "usage: $0 [debug|release]" >&2; exit 2 ;;
esac

[[ -x "$GODOT" ]] || { echo "ERROR: Godot not found at $GODOT" >&2; exit 127; }

# ---------------------------------------------------------------- release key
ensure_release_keystore() {
  if [[ -f "$KEYSTORE" && -f "$PROPS" ]]; then
    return
  fi
  echo "[build] generating release keystore (one time)"
  local pass
  pass="$(head -c 18 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 24)"
  "$JAVA_HOME/bin/keytool" -genkeypair -v \
    -keystore "$KEYSTORE" -alias microworkout \
    -storepass "$pass" -keypass "$pass" \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -dname "CN=MicroWorkout, OU=Personal, O=MicroWorkout, L=, ST=, C=US" >/dev/null 2>&1
  cat >"$PROPS" <<EOF
# Generated by tools/build_android.sh — DO NOT COMMIT (gitignored).
# Used to sign release builds. Lose this file and you cannot update an installed
# release APK in place; you would have to uninstall first.
KEYSTORE_PATH="$KEYSTORE"
KEYSTORE_ALIAS="microworkout"
KEYSTORE_PASSWORD="$pass"
EOF
  chmod 600 "$PROPS" "$KEYSTORE"
  echo "[build] keystore + credentials written to build/ (gitignored)"
}

patch_release_keystore() {
  # shellcheck disable=SC1090
  source "$PROPS"
  cp "$PRESETS" "$BUILD_DIR/export_presets.cfg.orig"
  python3 - "$PRESETS" "$KEYSTORE_PATH" "$KEYSTORE_ALIAS" "$KEYSTORE_PASSWORD" <<'PY'
import sys
path, ks, alias, pw = sys.argv[1:5]
with open(path) as fh:
    lines = fh.readlines()
out, in_release = [], False
for line in lines:
    if line.startswith("[preset."):
        in_release = line.strip() == "[preset.1.options]"
    if in_release:
        if line.startswith("keystore/release="):
            line = f'keystore/release="{ks}"\n'
        elif line.startswith("keystore/release_user="):
            line = f'keystore/release_user="{alias}"\n'
        elif line.startswith("keystore/release_password="):
            line = f'keystore/release_password="{pw}"\n'
    out.append(line)
with open(path, "w") as fh:
    fh.writelines(out)
PY
  # The trap is the single owner of the restore. Doing the restore here as well caused a
  # double-move that made an otherwise successful build exit non-zero.
  trap 'if [[ -f "$BUILD_DIR/export_presets.cfg.orig" ]]; then mv -f "$BUILD_DIR/export_presets.cfg.orig" "$PRESETS"; fi' EXIT
}

if [[ "$MODE" == "release" ]]; then
  ensure_release_keystore
  patch_release_keystore
fi

# ------------------------------------------------------------------- export
rm -f "$OUT"
echo "[build] exporting '$PRESET' -> $OUT"
set +e
"$GODOT" --headless --path "$ROOT" $FLAG "$PRESET" "$OUT" 2>&1 | tee "$BUILD_DIR/export.log" | grep -viE "^\s*$" | tail -30
STATUS="${PIPESTATUS[0]}"
set -e

if [[ "$STATUS" -ne 0 || ! -f "$OUT" ]]; then
  echo "[build] FAILED — export exit=$STATUS, APK $([[ -f "$OUT" ]] && echo present || echo missing). See $BUILD_DIR/export.log" >&2
  exit 1
fi

# A release APK is only useful when it is actually signed. Godot's exporter once
# finished with a signing warning and still left an unsigned file behind, so the
# release build verifies the signature before declaring success (PRD-13 R4).
if [[ "$MODE" == "release" ]]; then
  APKSIGNER="$(ls -d "$ANDROID_HOME"/build-tools/*/apksigner 2>/dev/null | sort -V | tail -1 || true)"
  if [[ -z "$APKSIGNER" ]]; then
    echo "[build] FAILED — apksigner not found under $ANDROID_HOME/build-tools" >&2
    exit 1
  fi
  if ! "$APKSIGNER" verify "$OUT" >/dev/null 2>&1; then
    echo "[build] FAILED — $OUT is NOT signed. See $BUILD_DIR/export.log" >&2
    exit 1
  fi
  echo "[build] signature verified"
fi

SIZE_BYTES="$(stat -c%s "$OUT")"
SIZE_MB="$(awk -v b="$SIZE_BYTES" 'BEGIN{printf "%.2f", b/1048576}')"
echo "[build] OK  $(basename "$OUT")  ${SIZE_MB} MB (${SIZE_BYTES} bytes)"
echo "$SIZE_MB" > "$BUILD_DIR/last_apk_size_mb.txt"
echo "APK size: ${SIZE_MB} MB"

# PRD-12 R11 — the size gate. The release APK's budget is ≤ 60 MB target and ≤ 75 MB hard
# ceiling; AC12 requires this script to fail above the ceiling rather than report a number
# nobody checks. ALLOW_OVERSIZE=1 is the documented escape hatch (and the perf report's P8 row
# reads the same number out of this output).
if [[ "$MODE" == "release" ]]; then
  if awk -v size="$SIZE_MB" 'BEGIN { exit !(size > 75.0) }'; then
    if [[ "${ALLOW_OVERSIZE:-0}" == "1" ]]; then
      echo "[build] WARNING — ${SIZE_MB} MB exceeds the 75 MB ceiling (ALLOW_OVERSIZE=1)" >&2
    else
      echo "[build] FAILED — ${SIZE_MB} MB exceeds the 75 MB ceiling (PRD-12 R11)." >&2
      echo "[build]   Levers, in order: drop an ABI, PNG compress/mode=1, PRD-04's art ladder," >&2
      echo "[build]   WebP q80 (ADR), or a 'lite' preset. ALLOW_OVERSIZE=1 overrides." >&2
      exit 1
    fi
  elif awk -v size="$SIZE_MB" 'BEGIN { exit !(size > 60.0) }'; then
    echo "[build] NOTE — ${SIZE_MB} MB is over the 60 MB target but under the 75 MB ceiling"
  fi
fi
