#!/usr/bin/env bash
# MicroWorkout — Android APK build (PRD-00 §10 layer 4).
#
#   tools/build_android.sh debug     -> build/MicroWorkout-debug.apk  (unsigned-with-debug-key)
#   tools/build_android.sh release   -> build/MicroWorkout.apk        (signed with our release key)
#
# Uses the PREBUILT export template (gradle_build=false) because this machine has
# no Android NDK — see master plan §3 and ADR-01.
#
# The release keystore password never lives in git: it is generated once into
# build/keystore.properties (gitignored) and injected into export_presets.cfg only
# for the duration of the export.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GODOT="${GODOT_BIN:-$HOME/Applications/godot}"
export JAVA_HOME="${JAVA_HOME:-$HOME/dev/jdk-17}"
export ANDROID_HOME="${ANDROID_HOME:-$HOME/Android/Sdk}"
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export PATH="$JAVA_HOME/bin:$ANDROID_HOME/platform-tools:$PATH"

MODE="${1:-debug}"
BUILD_DIR="$ROOT/build"
PROPS="$BUILD_DIR/keystore.properties"
KEYSTORE="$BUILD_DIR/microworkout-release.keystore"
PRESETS="$ROOT/export_presets.cfg"

mkdir -p "$BUILD_DIR"

case "$MODE" in
  debug)   PRESET="Android Debug";   OUT="$BUILD_DIR/MicroWorkout-debug.apk"; FLAG="--export-debug" ;;
  release) PRESET="Android Release"; OUT="$BUILD_DIR/MicroWorkout.apk";       FLAG="--export-release" ;;
  *) echo "usage: $0 [debug|release]" >&2; exit 2 ;;
esac

[[ -x "$GODOT" ]] || { echo "ERROR: Godot not found at $GODOT" >&2; exit 127; }

# ---------------------------------------------------------------- release key
ensure_release_keystore() {
  if [[ -f "$KEYSTORE" && -f "$PROPS" ]]; then
    return
  fi
  echo "[build] generating release keystore (one time)"
  local pass
  pass="$(head -c 18 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 24)"
  "$JAVA_HOME/bin/keytool" -genkeypair -v \
    -keystore "$KEYSTORE" -alias microworkout \
    -storepass "$pass" -keypass "$pass" \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -dname "CN=MicroWorkout, OU=Personal, O=MicroWorkout, L=, ST=, C=US" >/dev/null 2>&1
  cat >"$PROPS" <<EOF
# Generated by tools/build_android.sh — DO NOT COMMIT (gitignored).
# Used to sign release builds. Lose this file and you cannot update an installed
# release APK in place; you would have to uninstall first.
KEYSTORE_PATH="$KEYSTORE"
KEYSTORE_ALIAS="microworkout"
KEYSTORE_PASSWORD="$pass"
EOF
  chmod 600 "$PROPS" "$KEYSTORE"
  echo "[build] keystore + credentials written to build/ (gitignored)"
}

patch_release_keystore() {
  # shellcheck disable=SC1090
  source "$PROPS"
  cp "$PRESETS" "$BUILD_DIR/export_presets.cfg.orig"
  python3 - "$PRESETS" "$KEYSTORE_PATH" "$KEYSTORE_ALIAS" "$KEYSTORE_PASSWORD" <<'PY'
import sys
path, ks, alias, pw = sys.argv[1:5]
with open(path) as fh:
    lines = fh.readlines()
out, in_release = [], False
for line in lines:
    if line.startswith("[preset."):
        in_release = line.strip() == "[preset.1.options]"
    if in_release:
        if line.startswith("keystore/release="):
            line = f'keystore/release="{ks}"\n'; continue
        if line.startswith("keystore/release_user="):
            line = f'keystore/release_user="{alias}"\n'; continue
        if line.startswith("keystore/release_password="):
            line = f'keystore/release_password="{pw}"\n'; continue
    out.append(line)
with open(path, "w") as fh:
    fh.writelines(out)
PY
  # The trap is the single owner of the restore. Doing the restore here as well caused a
  # double-move that made an otherwise successful build exit non-zero.
  trap 'if [[ -f "$BUILD_DIR/export_presets.cfg.orig" ]]; then mv -f "$BUILD_DIR/export_presets.cfg.orig" "$PRESETS"; fi' EXIT
}

if [[ "$MODE" == "release" ]]; then
  ensure_release_keystore
  patch_release_keystore
fi

# ------------------------------------------------------------------- export
rm -f "$OUT"
echo "[build] exporting '$PRESET' -> $OUT"
set +e
"$GODOT" --headless --path "$ROOT" $FLAG "$PRESET" "$OUT" 2>&1 | tee "$BUILD_DIR/export.log" | grep -viE "^\s*$" | tail -30
STATUS="${PIPESTATUS[0]}"
set -e

if [[ ! -f "$OUT" ]]; then
  echo "[build] FAILED — no APK produced (exit $STATUS). See $BUILD_DIR/export.log" >&2
  exit 1
fi

SIZE_BYTES="$(stat -c%s "$OUT")"
SIZE_MB="$(awk -v b="$SIZE_BYTES" 'BEGIN{printf "%.2f", b/1048576}')"
echo "[build] OK  $(basename "$OUT")  ${SIZE_MB} MB (${SIZE_BYTES} bytes)"
echo "$SIZE_MB" > "$BUILD_DIR/last_apk_size_mb.txt"
