#!/usr/bin/env bash
# MicroWorkout — regenerate the GDScript compile sweep, then (headless) parse it.
#
#   tools/check_warnings.sh
#
# The sweep is `scripts/dev/_compile_check.gd`: it `preload()`s **every** script under `scripts/`,
# which forces the parser to compile all of them — including files the boot path never reaches
# (`generator.gd`, `llm.gd`, a new screen). Both it and `scenes/dev_compile_check.tscn` are
# gitignored, so they are regenerated here rather than committed.
#
# ⚠️ **`--headless` does not emit GDScript static warnings at all** (see docs/RESUME.md §4), so this
# script's `--headless --quit` line is only a parse check. The real warning gate is the MCP run:
#
#   mcp__godot__run_project(projectPath, scene="res://scenes/dev_compile_check.tscn")
#   mcp__godot__get_debug_output      # -> "errors" must be []
#
# which supplies a real GL context and collects the buffer while the scene holds the process open.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GODOT="${GODOT_BIN:-$HOME/Applications/godot}"
SWEEP_SCRIPT="$ROOT/scripts/dev/_compile_check.gd"
SWEEP_SCENE="$ROOT/scenes/dev_compile_check.tscn"

cd "$ROOT"

mapfile -t FILES < <(find scripts -name '*.gd' ! -name '_compile_check.gd' | sort)
COUNT=${#FILES[@]}
if [[ "$COUNT" -eq 0 ]]; then
  echo "ERROR: no scripts found under scripts/" >&2
  exit 1
fi

{
  cat <<'HEADER'
extends Node
## GENERATED by tools/check_warnings.sh — do not edit, do not commit.
## Preloading every script forces the parser to compile all of them, which is the only
## way to surface GDScript static warnings for code the default scene never reaches.
##
## The scene holds the process open for a few seconds because quitting inside `_ready()`
## exits before an MCP `get_debug_output` reader can collect the buffer, which reads as
## "No active Godot process":
##
##   mcp__godot__run_project(projectPath, scene="res://scenes/dev_compile_check.tscn")
##   mcp__godot__get_debug_output      # errors must be []
HEADER
  echo ""
  echo "## How long the gate stays readable, in seconds."
  echo "const HOLD_SEC := 6.0"
  echo ""
  index=1
  for file in "${FILES[@]}"; do
    printf 'const _S%03d := preload("res://%s")\n' "$index" "$file"
    index=$((index + 1))
  done
  cat <<'FOOTER'

func _ready() -> void:
	print("[compile] preloaded %d script(s) without error" % <%COUNT>)
	await get_tree().create_timer(HOLD_SEC).timeout
	get_tree().quit(0)
FOOTER
} > "$SWEEP_SCRIPT"
# The count is baked in last so the printed number and the preload list cannot drift apart silently.
python3 - "$SWEEP_SCRIPT" "$COUNT" <<'PY'
import sys
path, count = sys.argv[1], sys.argv[2]
text = open(path).read().replace("<%COUNT>", count)
open(path, "w").write(text)
PY

mkdir -p scenes
cat > "$SWEEP_SCENE" <<'SCENE'
[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/dev/_compile_check.gd" id="1_c"]

[node name="CompileCheck" type="Node"]
script = ExtResource("1_c")
SCENE

echo "[check_warnings] regenerated $SWEEP_SCRIPT ($COUNT scripts) + $SWEEP_SCENE"

if [[ ! -x "$GODOT" ]]; then
  echo "ERROR: Godot binary not found at $GODOT (override with GODOT_BIN)" >&2
  exit 127
fi

"$GODOT" --headless --path "$ROOT" --import >/dev/null 2>&1 || true
echo "[check_warnings] parse check (this mode cannot see warnings — use the MCP gate):"
"$GODOT" --headless --path "$ROOT" --quit 2>&1 | grep -E "SCRIPT ERROR|Parse Error|Compile Error" || echo "  no parse errors"
